name: Build and test Paginate

on:
  push:
    branches-ignore:
      - main
  workflow_call:

env:
  DOTNET_VERSION: 8.0.x

jobs:
  build-paginate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup .NET Core SDK ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - name: Add GH package source, restore, build and test
        run: |
          dotnet nuget add source --username DEMGroup --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github.com "https://nuget.pkg.github.com/DEMGroup/index.json"
          dotnet restore -r linux-x64
          dotnet build -v=q --configuration Release --no-restore
          dotnet test --no-restore --no-build --logger trx --results-directory TestResults
      - name: Check Test File Exists
        if: success() || failure()
        id: hasTests
        run: |
          if compgen -G "TestResults/*.trx" > /dev/null; then
            hasTest=true
          else
            hasTest=false
          fi
          echo "hasTests=$hasTest" >> $GITHUB_OUTPUT
      - name: Test Reporter
        if: ${{ steps.hasTests.outputs.hasTests == 'true' }}
        uses: phoenix-actions/test-reporting@v10
        with:
          name: ${{github.repository}} Test Results
          path: TestResults/*.trx
          reporter: dotnet-trx
          output-to: step-summary
